### ISSUE TITLE
zeromz and jzmq packages not found

### ISSUE THREAD

**Issue by lorenwest** [Webtrends/Cookbooks#3]
Hello,  we're trying to intall on ubuntu 12.04 on EC2, and it's saying the zeromq and jzmq packages cannot be found.

Do we need to specify an apt-repository that has these assets in them?

Thank you,
-Loren

**Comment by tas50** [comment]
The packages are included in the recipe directory but must be added to a repo or installed manually

**Comment by lorenwest** [comment]
I see them now - in the debs directory.  Thanks!
(maybe include a note in the README about installation)
