### ISSUE TITLE
Is the zookeeper license correct?

### ISSUE THREAD

**Issue by andy-leonard** [Webtrends/Cookbooks#5]
I noticed that the zookeeper license in its metadata.rb file is set as "All rights reserved" while every other cookbook that I checked is Apache 2.  Is this correct?

Thanks,
Andy

**Comment by tas50** [comment]
That was a mistake at the time the cookbook was created.  It should get fixed.

**Comment by andy-leonard** [comment]
Thanks for the clarification - much appreciated!
